### ISSUE TITLE
Epic enhancements to predator prey

### ISSUE THREAD

**Issue by rusu24edward** [rusu24edward/amber#52]
Add enhancements to predator prey environment:
- [x] Attack distance (done in #56)
- [x] Move distance (done in #58)
- [X] Observation distance
- [X] Communication channels (done in #79)
- [x] Customizable reward mappings per agent/agent_type (done in #72)

Cannot apply tabular learning until #63
